// Sumar items adicionales a temas sin fotos.
// También crea los JSON de los nuevos temas (hogar-*, personas-aficiones, etc.)
import { readFileSync, writeFileSync, existsSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const norm = (s) => s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]/g, "");

const lists = {
  "tenis-torneos": [
    "Wimbledon","Roland Garros","US Open","Australian Open","Copa Davis","Billie Jean King Cup",
    "ATP Finals","WTA Finals","Indian Wells","Miami Open","Mutua Madrid Open","Italian Open Roma",
    "Monte Carlo","Barcelona Open","Hamburgo","Toronto","Cincinnati","Shanghai","París Bercy",
    "Doha","Dubai","Acapulco","Rotterdam","Estocolmo","Stuttgart","Halle","Queens","Newport",
    "Atlanta","Washington Open","Winston-Salem","Beijing","Tokyo","Basilea","Marsella","Montpellier",
    "Sofia","Buenos Aires","Río Abierto","Santiago Open","Umag","Bastad","Gstaad","Kitzbühel",
    "Stuttgart Indoor","Adelaida","Brisbane","ATP Cup","Hopman Cup","United Cup","Laver Cup",
  ],
  "ciclismo-carreras": [
    "Tour de Francia","Giro de Italia","Vuelta a España","Mundial de Ciclismo","París-Roubaix",
    "Lieja-Bastoña-Lieja","Milán-San Remo","Tour de Flandes","La Flecha Valona","Strade Bianche",
    "Tirreno-Adriático","París-Niza","Vuelta al País Vasco","Vuelta a Cataluña","Vuelta a Andalucía",
    "Vuelta a Castilla y León","Critérium del Dauphiné","Tour de Suiza","Tour Down Under",
    "Vuelta a San Juan","Clásica de San Sebastián","Volta a Algarve","Volta a Portugal",
    "Vuelta a Burgos","Tour de Polonia","Critérium International","Volta a Catalunya","Trofeo Mallorca",
    "Volta a Comunitat Valenciana","Vuelta a Murcia","Vuelta a la Comunidad Valenciana",
    "Gran Piemonte","Giro di Lombardia","Tres Días de La Panne","Gent-Wevelgem","Brabantse Pijl",
    "Tour de Yorkshire","Tour de Wallonie","Tour of Britain","Tour of California","Tour de Pologne",
    "Settimana Coppi e Bartali","Vuelta a Asturias","Vuelta a Aragón","Vuelta a Castilla la Mancha",
    "Memorial Marco Pantani",
  ],
  "f1-equipos": [
    "Ferrari","Mercedes","Red Bull Racing","McLaren","Williams","Aston Martin","Alpine",
    "Racing Bulls","Stake F1 Sauber","Haas","Audi (futuro)","Renault","Toro Rosso","AlphaTauri",
    "Honda","Lotus","BAR","BMW Sauber","Jaguar","Stewart","Tyrrell","Brabham","Cooper","BRM",
    "Lola","March","Ligier","Toleman","Minardi","Arrows","Footwork","Forti","Pacific","Andrea Moda",
    "Life","Coloni","AGS","EuroBrun","Onyx","Larrousse","Surtees","Wolf","Hesketh","Penske",
    "Shadow","Ensign","Spirit","Zakspeed","Osella","Rial",
  ],
  "golf-jugadores": [
    "Tiger Woods","Phil Mickelson","Jack Nicklaus","Arnold Palmer","Gary Player","Tom Watson",
    "Ben Hogan","Sam Snead","Bobby Jones","Walter Hagen","Lee Trevino","Rory McIlroy","Jordan Spieth",
    "Justin Thomas","Brooks Koepka","Dustin Johnson","Bryson DeChambeau","Patrick Cantlay",
    "Xander Schauffele","Scottie Scheffler","Hideki Matsuyama","Cameron Smith","Jon Rahm",
    "Sergio García","Severiano Ballesteros","José María Olazábal","Miguel Ángel Jiménez",
    "Pablo Larrazábal","Jorge Campillo","Adri Arnaus","Henrik Stenson","Tommy Fleetwood",
    "Padraig Harrington","Justin Rose","Lee Westwood","Ian Poulter","Luke Donald","Colin Montgomerie",
    "Nick Faldo","Sandy Lyle","Ernie Els","Vijay Singh","Adam Scott","Jason Day","Annika Sörenstam",
    "Lorena Ochoa","Inbee Park","Lydia Ko","Carlota Ciganda","Azahara Muñoz",
  ],
  "ciclismo-conceptos": [
    "Etapa","Tour","Vuelta","Maillot amarillo","Maillot verde","Maillot rojo","Maillot de lunares",
    "Maillot blanco","Maillot rosa","Esprint","Embalaje","Contrarreloj","Crono individual",
    "Crono por equipos","Equipo","Director deportivo","Líder","Gregario","Escapada","Pelotón",
    "Bonificación","Bonificación de meta","Línea de meta","Línea de salida","Dorsal","Bidón",
    "Casco","Manillar","Cambio","Plato","Piñón","Cadena","Pedal","Sillín","Llanta","Cubierta",
    "Tubular","Maillot","Culotte","Guantes","Gafas","Calas","Cuentakilómetros","Pulsómetro",
    "Potenciómetro","GPS","Avituallamiento","Coche de equipo","Moto neutra","UCI","Cofidis",
    "Movistar Team","Jumbo-Visma","Soudal-Quick-Step","INEOS Grenadiers","UAE Team Emirates",
    "Bora-Hansgrohe","Lidl-Trek","Decathlon AG2R","Etapa de montaña","Alta montaña","Puerto",
    "Bajada","Vivac",
  ],
  "golf-conceptos": [
    "Hoyo","Green","Fairway","Rough","Búnker","Tee","Bandera","Bola","Palo","Hierro","Madera",
    "Putter","Wedge","Driver","Swing","Putt","Approach","Chip","Drive","Birdie","Eagle","Albatros",
    "Bogey","Doble bogey","Triple bogey","Par","Hoyo en uno","Slice","Hook","Draw","Fade","Push",
    "Pull","Caddie","Vuelta","Stroke play","Match play","Foursome","Hándicap","PGA Tour",
    "European Tour","LPGA","Masters de Augusta","US Open","British Open","PGA Championship",
    "Ryder Cup","Solheim Cup","Presidents Cup","Augusta National","St Andrews","Pebble Beach",
    "Pinehurst","Carnoustie","Royal Birkdale","Bethpage","Whistling Straits","Quail Hollow",
    "Doral","TPC Sawgrass","Bay Hill","Memorial","Greenkeeper","Marker",
  ],
  "motor-conceptos": [
    "Fórmula 1","MotoGP","Moto2","Moto3","MotoE","NASCAR","IndyCar","WEC","WRC","Dakar","Le Mans 24h",
    "Gran Premio","Pole position","Vuelta rápida","Podio","Bandera a cuadros","Bandera amarilla",
    "Bandera roja","Bandera azul","Bandera verde","Safety Car","Virtual Safety Car","Pit stop","Box",
    "Falsa salida","Stop & Go","Drive-through","Penalty","Curva en herradura","Chicane","Recta",
    "Curva","Apex","Línea de carrera","Slipstream","DRS","Halo","Aerodinámica","Alerón","Difusor",
    "Bargeboard","Casco","Mono","HANS","FIA","Fórmula E","Rally","Karting","Stock car","Drift",
    "Hot lap","Race start","Race control","Pole","Stewards","Sprint","Race weekend","Free Practice",
    "Qualifying","Sprint Shootout",
  ],
  "teatro-autores": [
    "William Shakespeare","Molière","Lope de Vega","Calderón de la Barca","Tirso de Molina",
    "Federico García Lorca","Antonio Buero Vallejo","Alejandro Casona","Miguel Mihura",
    "Enrique Jardiel Poncela","Jacinto Benavente","Valle-Inclán","Antonio Gala","Juan Mayorga",
    "Sergi Belbel","Lluïsa Cunillé","Pau Miró","Ernesto Caballero","José Sanchis Sinisterra",
    "Anton Chéjov","Henrik Ibsen","August Strindberg","Bertolt Brecht","Tennessee Williams",
    "Arthur Miller","Eugene O'Neill","David Mamet","Sam Shepard","Tom Stoppard","Harold Pinter",
    "Edward Albee","Samuel Beckett","Eugène Ionesco","Jean Genet","Jean-Paul Sartre","Albert Camus",
    "Luigi Pirandello","Dario Fo","Yasmina Reza","Florian Zeller","Carlo Goldoni","August Wilson",
    "Lillian Hellman","George Bernard Shaw","Oscar Wilde","Bernard-Marie Koltès","Heiner Müller",
    "Jean Anouilh","Alfonso Sastre",
  ],
  "tenis-conceptos": [
    "Saque","Resto","Ace","Doble falta","Drive","Revés","Volea","Smash","Globo","Dejada",
    "Passing shot","Bola de break","Bola de partido","Bola de set","Tie-break","Set","Juego",
    "Punto","Game","Deuce","Ventaja","Iguales","Foot fault","Net cord","Línea","Pista","Cancha",
    "Red","Banda","Pista de tierra","Pista dura","Hierba","Pista cubierta","Indoor","Outdoor",
    "Hawk-Eye","Challenge","Match point","Triple bagel","Bagel","Mini-break","Tweener","ATP","WTA",
    "ITF","Grand Slam","Masters 1000","ATP 500","ATP 250","Ranking","Cabeza de serie","Wildcard",
    "Qualy","Bye","Top 10","Top 100",
  ],
  "lit-poetas": [
    "Federico García Lorca","Antonio Machado","Miguel Hernández","Rafael Alberti","Juan Ramón Jiménez",
    "Pedro Salinas","Vicente Aleixandre","Luis Cernuda","Jorge Guillén","Gerardo Diego","Gabriel Celaya",
    "Blas de Otero","José Hierro","Gloria Fuertes","Ángel González","Rosalía de Castro",
    "Gustavo Adolfo Bécquer","José de Espronceda","Rubén Darío","Pablo Neruda","Gabriela Mistral",
    "Octavio Paz","Mario Benedetti","Nicolás Guillén","César Vallejo","Vicente Huidobro",
    "Alfonsina Storni","Sor Juana Inés de la Cruz","Garcilaso de la Vega","Quevedo","Góngora",
    "Fray Luis de León","San Juan de la Cruz","Santa Teresa de Jesús","Carlos Edmundo de Ory",
    "José Ángel Valente","Claudio Rodríguez","Francisco Brines","Antonio Gamoneda",
    "Luis Alberto de Cuenca","Joan Margarit","Joan Maragall","Salvador Espriu","Walt Whitman",
    "Emily Dickinson","Edgar Allan Poe","Charles Baudelaire","Arthur Rimbaud","Paul Verlaine",
  ],
  "marcas-lujo": [
    "Louis Vuitton","Gucci","Chanel","Hermès","Prada","Dior","Versace","Cartier","Rolex",
    "Tiffany & Co.","Bvlgari","Burberry","Fendi","Armani","Yves Saint Laurent","Dolce & Gabbana",
    "Valentino","Balenciaga","Givenchy","Carolina Herrera","Tom Ford","Ralph Lauren","Calvin Klein",
    "Hugo Boss","Salvatore Ferragamo","Loewe","Bottega Veneta","Loro Piana","Brunello Cucinelli",
    "Off-White","Stone Island","Moncler","Canada Goose","Ermenegildo Zegna","Patek Philippe",
    "Audemars Piguet","Vacheron Constantin","Omega","Tag Heuer","Breitling","IWC","Hublot",
    "Jaeger-LeCoutre","Panerai","Longines","Tudor","Richard Mille","Lange & Söhne","Piaget","Chopard",
  ],
  "moda-disenadores": [
    "Coco Chanel","Christian Dior","Yves Saint Laurent","Karl Lagerfeld","Giorgio Armani",
    "Donatella Versace","Gianni Versace","Tom Ford","Marc Jacobs","Stella McCartney",
    "Vivienne Westwood","Vera Wang","Donna Karan","Calvin Klein","Ralph Lauren","Tommy Hilfiger",
    "Alexander McQueen","John Galliano","Jean Paul Gaultier","Hubert de Givenchy","Isaac Mizrahi",
    "Oscar de la Renta","Carolina Herrera","Diane von Fürstenberg","Manolo Blahnik","Jimmy Choo",
    "Cristóbal Balenciaga","Manuel Pertegaz","Adolfo Domínguez","Jesús del Pozo",
    "Ágatha Ruiz de la Prada","Roberto Verino","Custo Barcelona","Amaya Arzuaga","Antonio Miró",
    "Ángel Schlesser","Lorenzo Caprile","Hannibal Laguna","Juan Vidal","Sybilla","Devota & Lomba",
    "Pedro del Hierro","Paco Rabanne","Manolo Blahnik","Carmen March","Felipe Varela",
    "Lorenzo Caprile","Vicky Martín Berrocal",
  ],
  "moda-marcas": [
    "Zara","Mango","Bershka","Pull&Bear","Stradivarius","Massimo Dutti","Oysho","Lefties","H&M",
    "Uniqlo","Forever 21","ASOS","COS","& Other Stories","Primark","C&A","Decimas","Sprinter",
    "Decathlon","Carolina Herrera","Loewe","El Ganso","Scalpers","Silbón","Tommy Hilfiger",
    "Ralph Lauren","Lacoste","Hugo Boss","Diesel","Levi's","Wrangler","Lee","Gap","Banana Republic",
    "Old Navy","Abercrombie & Fitch","American Eagle","Hollister","Patagonia","The North Face",
    "Columbia","Quiksilver","Billabong","Rip Curl","O'Neill","Hurley","Volcom","Element","Vans",
    "Converse","Reebok","Nike","Adidas","Puma","Onitsuka Tiger",
  ],
  "personas-emociones": [
    "Alegría","Tristeza","Enfado","Sorpresa","Miedo","Asco","Vergüenza","Aburrimiento","Celos",
    "Amor","Ansiedad","Calma","Confianza","Frustración","Nostalgia","Orgullo","Culpa","Curiosidad",
    "Esperanza","Envidia","Felicidad","Euforia","Diversión","Risa","Llanto","Ira","Furia","Rabia",
    "Odio","Compasión","Empatía","Lástima","Pena","Soledad","Melancolía","Inseguridad","Timidez",
    "Asombro","Admiración","Desprecio","Indiferencia","Cansancio","Estrés","Tensión","Excitación",
    "Alivio","Satisfacción","Decepción","Optimismo","Pesimismo","Cariño","Ternura","Pasión","Pánico",
    "Agradecimiento","Resentimiento",
  ],
  "teatro-obras": [
    "Romeo y Julieta","Hamlet","Macbeth","El Rey Lear","Otelo","Sueño de una noche de verano",
    "La Tempestad","Mucho ruido y pocas nueces","El mercader de Venecia","La fierecilla domada",
    "Bodas de sangre","Yerma","La casa de Bernarda Alba","Doña Rosita la soltera",
    "La zapatera prodigiosa","Mariana Pineda","El público","Don Juan Tenorio","La vida es sueño",
    "El alcalde de Zalamea","Fuenteovejuna","El burlador de Sevilla","El médico a palos",
    "El sí de las niñas","Tres sombreros de copa","Historia de una escalera",
    "Las bicicletas son para el verano","Bajarse al moro","Eloísa está debajo de un almendro",
    "Antígona","Edipo Rey","Las tres hermanas","El jardín de los cerezos","El tío Vania","Tartufo",
    "El misántropo","El avaro","Casa de muñecas","Un enemigo del pueblo","Hedda Gabler",
    "Esperando a Godot","Un tranvía llamado Deseo","El zoo de cristal","La muerte de un viajante",
    "Las brujas de Salem","Long Day's Journey","Cyrano de Bergerac","La cantante calva",
  ],
  "lit-escritores-espana": [
    "Miguel de Cervantes","Lope de Vega","Calderón de la Barca","Quevedo","Góngora",
    "Garcilaso de la Vega","Tirso de Molina","Mariano José de Larra","Espronceda","Bécquer",
    "Galdós","Clarín","Emilia Pardo Bazán","Unamuno","Pío Baroja","Azorín","Valle-Inclán",
    "Antonio Machado","Manuel Machado","Federico García Lorca","Miguel Hernández","Rafael Alberti",
    "Juan Ramón Jiménez","Camilo José Cela","Miguel Delibes","Carmen Laforet","Carmen Martín Gaite",
    "Ana María Matute","Gonzalo Torrente Ballester","Francisco Ayala","Jorge Semprún",
    "Ramón J. Sender","Vázquez Montalbán","Juan Marsé","Eduardo Mendoza","Antonio Muñoz Molina",
    "Javier Marías","Almudena Grandes","Arturo Pérez-Reverte","Carlos Ruiz Zafón","Ildefonso Falcones",
    "Julia Navarro","Dolores Redondo","Rosa Montero","Elvira Lindo","Manuel Vicent","Vicente Aleixandre",
    "Pedro Salinas","Jorge Guillén","Luis Cernuda",
  ],
  "lit-personajes": [
    "Don Quijote","Sancho Panza","Dulcinea","La Celestina","Lazarillo de Tormes","Don Juan",
    "El Buscón","Tom Sawyer","Huckleberry Finn","Oliver Twist","David Copperfield","Sherlock Holmes",
    "Doctor Watson","Hércules Poirot","Miss Marple","Robinson Crusoe","Robin Hood","Capitán Garfio",
    "Peter Pan","Alicia","Frankenstein","Drácula","Edmond Dantès","Jean Valjean","Cosette",
    "Madame Bovary","Anna Karenina","Raskolnikov","Mr. Darcy","Elizabeth Bennet","Heathcliff",
    "Jane Eyre","Hester Prynne","Holden Caulfield","Atticus Finch","Scout Finch","Gandalf","Frodo",
    "Sam","Aragorn","Gollum","Harry Potter","Hermione Granger","Ron Weasley","Voldemort",
    "Albus Dumbledore","Bilbo Bolsón","Aslan","Lucy Pevensie","Werther","El Principito",
  ],
  "ciclismo-leyendas": [
    "Miguel Induráin","Pedro Delgado","Federico Bahamontes","José Manuel Fuente","Luis Ocaña",
    "Alberto Contador","Carlos Sastre","Óscar Freire","Joaquim Rodríguez","Alejandro Valverde",
    "Samuel Sánchez","Mikel Landa","Enric Mas","Jonas Vingegaard","Tadej Pogačar","Eddy Merckx",
    "Bernard Hinault","Jacques Anquetil","Lance Armstrong","Greg LeMond","Fausto Coppi","Gino Bartali",
    "Felice Gimondi","Francesco Moser","Sean Kelly","Stephen Roche","Andy Hampsten","Marco Pantani",
    "Mario Cipollini","Erik Zabel","Robbie McEwen","Mark Cavendish","Peter Sagan","Fabio Aru",
    "Vincenzo Nibali","Chris Froome","Bradley Wiggins","Geraint Thomas","Egan Bernal","Wout Van Aert",
    "Mathieu Van der Poel","Primoz Roglic","Remco Evenepoel","Filippo Ganna","Tom Boonen",
    "Fabian Cancellara",
  ],
  "personas-familia": [
    "Madre","Padre","Hijo","Hija","Hermano","Hermana","Abuelo","Abuela","Nieto","Nieta","Tío","Tía",
    "Primo","Prima","Sobrino","Sobrina","Cuñado","Cuñada","Suegro","Suegra","Yerno","Nuera",
    "Padrastro","Madrastra","Bisabuelo","Bisabuela","Bisnieto","Bisnieta","Hermanastro","Hermanastra",
    "Hijastro","Hijastra","Mellizos","Gemelos","Trillizos","Padrino","Madrina","Ahijado","Ahijada",
    "Novio","Novia","Esposo","Esposa","Marido","Mujer","Pareja","Soltero","Casado","Divorciado",
    "Viudo","Separado","Pariente","Familia adoptiva","Familia política","Tatarabuelo","Tatarabuela",
  ],
  "lit-libros": [
    "Don Quijote","La Celestina","Lazarillo de Tormes","El Buscón","Cien años de soledad",
    "El amor en los tiempos del cólera","La sombra del viento","El nombre de la rosa","El alquimista",
    "La piel del tambor","Los pilares de la tierra","El código Da Vinci","El psicoanalista","Patria",
    "El tiempo entre costuras","Asesinato en el Orient Express","Diez negritos","Frankenstein",
    "Drácula","El retrato de Dorian Gray","Las uvas de la ira","1984","Un mundo feliz","Fahrenheit 451",
    "Rebelión en la granja","El Señor de los Anillos","El Hobbit","Las crónicas de Narnia",
    "Harry Potter y la piedra filosofal","El Principito","Las aventuras de Tom Sawyer",
    "El Conde de Montecristo","Los miserables","Madame Bovary","Anna Karenina","Guerra y paz",
    "Crimen y castigo","Orgullo y prejuicio","Cumbres borrascosas","Jane Eyre","Moby Dick",
    "El viejo y el mar","Por quién doblan las campanas","La Regenta","Fortunata y Jacinta",
    "La Familia de Pascual Duarte","La Colmena","Mientras agonizo","El gran Gatsby",
  ],
  "marcas-juguetes": [
    "Barbie","Action Man","Mariquita Pérez","Bratz","Nancy","Monster High","LEGO","Playmobil",
    "Polly Pocket","Furby","Hot Wheels","Scalextric","LEGO Friends","Pinypon","Tente","Madelman",
    "Geyper Man","Famobil","My Little Pony","Tamagotchi","Beyblade","Trivial Pursuit","Risk",
    "Monopoly","Parchís","Operación","Cluedo","Domino","Lince","Pictionary","Catán","Carcassonne",
    "Ajedrez","Damas","Conecta 4","Tabú","Hasbro","Fisher-Price","Mattel","Famosa","Bandai",
    "Mega Bloks","K'Nex","Slime","Cubo de Rubik","Yoyo","Diábolo","Spinner","Peonza","Comba",
    "Cuerda de saltar",
  ],
  "personas-influencers": [
    "Ibai Llanos","AuronPlay","El Rubius","Vegetta777","TheGrefg","Dulceida","Paula Gonu",
    "María Pombo","Marta Lozano","Laura Escanes","Lola Lolita","Marina Yers","Violeta Mangriñán",
    "Aida Domenech","Pelayo Díaz","Tomás Páramo","Mister Jagger","Wismichu","Willyrex","DjMaRiiO",
    "MrBeast","Khaby Lame","Charli D'Amelio","Addison Rae","Bella Poarch","Logan Paul","Jake Paul",
    "PewDiePie","Markiplier","James Charles","Emma Chamberlain","Zoella","Kendall Jenner",
    "Kylie Jenner","Kim Kardashian","Cristina Pedroche","Anna Padilla","Marta Carriedo",
    "Alexandra Pereira","Sara Carbonero","Susi Caramelo","Inés Hernand","Soy Una Pringada",
    "Naím Darrechi","Andre Lamoglia","Adexe & Nau","Lalachus","Dani Mateo","David Broncano",
    "Manuel Burque","Quevedo","Bad Gyal",
  ],
  "personas-politicos": [
    "Pedro Sánchez","Mariano Rajoy","José Luis Rodríguez Zapatero","Felipe González","José María Aznar",
    "Adolfo Suárez","Manuela Carmena","Yolanda Díaz","Alberto Núñez Feijóo","Pablo Iglesias",
    "Santiago Abascal","Inés Arrimadas","Albert Rivera","Ada Colau","Isabel Díaz Ayuso","Donald Trump",
    "Joe Biden","Barack Obama","Emmanuel Macron","Angela Merkel","Vladímir Putin","Volodímir Zelenski",
    "Xi Jinping","Justin Trudeau","Giorgia Meloni","Olaf Scholz","Rishi Sunak","Keir Starmer",
    "Boris Johnson","David Cameron","Tony Blair","Margaret Thatcher","Nelson Mandela","Lula da Silva",
    "Jair Bolsonaro","Javier Milei","Kamala Harris","Hillary Clinton","Bill Clinton","George W. Bush",
    "Ronald Reagan","John F. Kennedy","Charles de Gaulle","François Hollande","Nicolas Sarkozy",
    "Silvio Berlusconi","Felipe VI","Letizia Ortiz","Juan Carlos I","Reina Sofía",
  ],
  "productos-complementos": [
    "Bolso","Mochila","Cartera","Monedero","Maleta","Sombrero","Gorra","Bufanda","Guantes",
    "Cinturón","Corbata","Pajarita","Collar","Pendientes","Anillo","Pulsera","Reloj","Gafas de sol",
    "Gafas graduadas","Paraguas","Pañuelo","Diadema","Coletero","Riñonera","Llavero","Pinzas pelo",
    "Horquillas","Cinta de pelo","Lazo","Tirantes","Hebilla","Broche","Anillo de boda","Sello",
    "Medalla","Cadena","Pulsera amuleto","Reloj de pulsera","Reloj de bolsillo","Reloj inteligente",
    "Sombrero de paja","Boina","Pamela","Capucha","Casco de moto","Casco de bici","Gorro de baño",
    "Velo","Bandana","Pasamontañas","Bolso de mano","Bandolera","Tote bag","Bolso de viaje",
  ],
  "productos-tecnologia": [
    "Móvil","Tablet","Portátil","Ordenador","Televisión","Smartwatch","Pulsera de actividad",
    "Auriculares","Altavoz","Cámara de fotos","Videocámara","E-book","Consola","Mando","Teclado",
    "Ratón","Pantalla","Impresora","Router","Cargador","Disco duro","USB","Robot aspirador","Drone",
    "Gafas de realidad virtual","Casco VR","Cámara web","Micrófono","Smart Speaker","Asistente virtual",
    "Termostato inteligente","Cerradura inteligente","Bombilla inteligente","Robot de cocina",
    "Thermomix","Olla programable","Air fryer","Aspiradora robot","Cafetera de cápsulas","Báscula inteligente",
    "Tensiómetro digital","Glucómetro","Sensor de movimiento","Cámara IP","Alarma","Power bank",
    "Cable USB-C","Cable HDMI","Adaptador","Hub USB",
  ],
  "productos-vehiculos": [
    "Coche","Moto","Bicicleta","Patinete","Patinete eléctrico","Camión","Furgoneta","Autobús","Tren",
    "Metro","Tranvía","Avión","Helicóptero","Barco","Yate","Velero","Submarino","Cohete",
    "Globo aerostático","Trineo","Quad","Karting","Caravana","Ambulancia","Coche de policía",
    "Motocicleta","Scooter","Vespa","Bicicleta de montaña","Bicicleta de carretera",
    "Bicicleta eléctrica","Monociclo","Triciclo","Tabla de skate","Tabla de surf","Esquí","Snowboard",
    "Tabla de paddle","Catamarán","Zódiac","Lancha motora","Crucero","Ferry","Bote","Piragua","Kayak",
    "Canoa","Hidroavión","Avioneta","Planeador","Parapente","Globo","Zepelín","Carruaje","Diligencia",
    "Tractor","Excavadora","Grúa","Cisterna",
  ],
  "deportes-olimpicos": [
    "Atletismo","100 metros lisos","200 metros","400 metros","800 metros","1500 metros","5000 metros",
    "10000 metros","Maratón","100 metros vallas","110 metros vallas","400 metros vallas",
    "Salto de altura","Salto con pértiga","Salto de longitud","Triple salto","Lanzamiento de peso",
    "Lanzamiento de disco","Lanzamiento de martillo","Lanzamiento de jabalina","Decatlón","Heptatlón",
    "Marcha","Natación","100 metros libres","Saltos de trampolín","Saltos de plataforma","Sincronizada",
    "Waterpolo","Vela","Remo","Piragüismo","Surf","Skateboard","Escalada","BMX","Ciclismo en pista",
    "Ciclismo en ruta","Mountain Bike","Gimnasia artística","Gimnasia rítmica","Trampolín",
    "Halterofilia","Lucha","Judo","Taekwondo","Karate","Boxeo","Esgrima","Tiro deportivo",
    "Tiro con arco","Tenis","Tenis de mesa","Bádminton","Voleibol","Voley playa","Balonmano",
    "Hockey hierba","Fútbol","Rugby 7","Triatlón",
  ],
  "f1-pilotos": [
    "Lewis Hamilton","Max Verstappen","Sebastian Vettel","Fernando Alonso","Carlos Sainz Jr.",
    "Charles Leclerc","Lando Norris","Oscar Piastri","George Russell","Sergio Pérez","Pierre Gasly",
    "Esteban Ocon","Yuki Tsunoda","Lance Stroll","Valtteri Bottas","Zhou Guanyu","Kevin Magnussen",
    "Nico Hülkenberg","Alex Albon","Logan Sargeant","Daniel Ricciardo","Kimi Räikkönen","Jenson Button",
    "Mark Webber","Felipe Massa","Rubens Barrichello","Michael Schumacher","Mika Häkkinen",
    "Nigel Mansell","Alain Prost","Ayrton Senna","Niki Lauda","Jackie Stewart","Stirling Moss",
    "Juan Manuel Fangio","Emerson Fittipaldi","Nelson Piquet","Jim Clark","Jack Brabham",
    "Jody Scheckter","Damon Hill","Jacques Villeneuve","Keke Rosberg","Nico Rosberg","Pedro de la Rosa",
    "Marc Gené","Roberto Merhi","Felipe Drugovich","Liam Lawson","Franco Colapinto",
  ],
  "tenis-jugadores": [
    "Rafael Nadal","Carlos Alcaraz","Novak Djokovic","Roger Federer","Andy Murray","Stan Wawrinka",
    "David Ferrer","Juan Carlos Ferrero","Sergi Bruguera","Manolo Santana","Arancha Sánchez Vicario",
    "Conchita Martínez","Garbiñe Muguruza","Paula Badosa","Pete Sampras","Andre Agassi","Boris Becker",
    "Stefan Edberg","Jimmy Connors","Ivan Lendl","John McEnroe","Björn Borg","Mats Wilander",
    "Marat Safin","Goran Ivanišević","Lleyton Hewitt","Gustavo Kuerten","Andy Roddick","Marin Čilić",
    "Juan Martín del Potro","Stefanos Tsitsipas","Daniil Medvedev","Alexander Zverev","Holger Rune",
    "Casper Ruud","Jannik Sinner","Andrey Rublev","Hubert Hurkacz","Felix Auger-Aliassime",
    "Denis Shapovalov","Taylor Fritz","Frances Tiafoe","Tommy Paul","Karen Khachanov","Cameron Norrie",
    "Serena Williams","Venus Williams","Steffi Graf","Martina Navratilova","Chris Evert","Monica Seles",
    "Maria Sharapova","Justine Henin","Kim Clijsters","Aryna Sabalenka","Iga Świątek","Coco Gauff",
    "Jessica Pegula","Naomi Osaka","Simona Halep","Petra Kvitová","Caroline Wozniacki",
    "Victoria Azarenka","Elena Rybakina",
  ],
  "lit-escritores-mundo": [
    "William Shakespeare","Charles Dickens","Jane Austen","Mark Twain","Edgar Allan Poe","Oscar Wilde",
    "James Joyce","Virginia Woolf","F. Scott Fitzgerald","Ernest Hemingway","George Orwell",
    "J.R.R. Tolkien","C.S. Lewis","Roald Dahl","Lewis Carroll","J.K. Rowling","Stephen King",
    "Agatha Christie","Arthur Conan Doyle","Bram Stoker","Mary Shelley","Daniel Defoe","Jonathan Swift",
    "Robert Louis Stevenson","Walt Whitman","Emily Dickinson","Vladimir Nabokov","Aldous Huxley",
    "J.D. Salinger","Harper Lee","Toni Morrison","John Steinbeck","William Faulkner","Cormac McCarthy",
    "Margaret Atwood","Kurt Vonnegut","Ray Bradbury","Isaac Asimov","Arthur C. Clarke","Philip K. Dick",
    "Frank Herbert","George R.R. Martin","Brandon Sanderson","Neil Gaiman","Terry Pratchett",
    "Douglas Adams","Italo Calvino","Umberto Eco","Elena Ferrante","Gabriel García Márquez",
    "Jorge Luis Borges","Julio Cortázar","Mario Vargas Llosa","Isabel Allende","Octavio Paz",
    "Pablo Neruda","Mario Benedetti","Roberto Bolaño","Luis Sepúlveda","Paulo Coelho","Jose Saramago",
    "Fernando Pessoa","Fyodor Dostoyevsky","Leo Tolstoy","Anton Chéjov","Alexander Pushkin",
    "Mikhail Bulgakov","Haruki Murakami","Kazuo Ishiguro","Yukio Mishima","Orhan Pamuk","Khaled Hosseini",
  ],
  "personas-historicos": [
    "Miguel de Cervantes","Francisco de Goya","Diego Velázquez","Pablo Picasso","Salvador Dalí",
    "Federico García Lorca","Lope de Vega","Cristóbal Colón","Hernán Cortés","Felipe II",
    "Isabel la Católica","Albert Einstein","Isaac Newton","Marie Curie","Nikola Tesla",
    "Leonardo da Vinci","Miguel Ángel","Ludwig van Beethoven","Wolfgang Amadeus Mozart",
    "William Shakespeare","Napoleón Bonaparte","Cleopatra","Julio César","Mahatma Gandhi",
    "Nelson Mandela","Abraham Lincoln","Winston Churchill","Juana de Arco","Galileo Galilei",
    "Charles Darwin","Sigmund Freud","Carl Jung","Karl Marx","Aristóteles","Platón","Sócrates",
    "Confucio","Sun Tzu","Genghis Khan","Alejandro Magno","Carlomagno","Enrique VIII",
    "Isabel I de Inglaterra","Reina Victoria","Tutankamón","Ramsés II","Nefertiti","Carlos V",
    "Felipe el Hermoso","Juana la Loca","María Antonieta","Luis XIV","Carlos III de España",
    "Fernando VII","Isabel II de España","Alfonso XIII","Francisco Franco","Adolf Hitler",
    "Iósif Stalin","Vladímir Lenin","Mao Zedong","Fidel Castro","Che Guevara","Eva Perón",
    "Simón Bolívar","Jorge Washington","Thomas Jefferson","Theodore Roosevelt","John F. Kennedy",
  ],
  "deportistas-espana": [
    "Rafa Nadal","Pau Gasol","Carlos Alcaraz","Marc Márquez","Fernando Alonso","Carlos Sainz Sr.",
    "Carlos Sainz Jr.","Mireia Belmonte","Alberto Contador","Andrés Iniesta","Sergio Ramos",
    "Iker Casillas","Carolina Marín","Garbiñe Muguruza","Paula Badosa","Marc Gasol","Ricky Rubio",
    "Sergio Llull","Felipe Reyes","Rudy Fernández","Juan Carlos Navarro","José Manuel Calderón",
    "Sandra Sánchez","Lydia Valentín","Saúl Craviotto","Marcus Cooper","Niko Sherazadishvili",
    "Bruno Hortelano","Orlando Ortega","Dani Pedrosa","Jorge Lorenzo","Sete Gibernau",
    "Maverick Viñales","Aleix Espargaró","Pol Espargaró","Joan Mir","Tito Rabat","Marc Gené",
    "Roberto Merhi","Severiano Ballesteros","José María Olazábal","Sergio García","Jon Rahm",
    "Xavi Hernández","Albert Costa","Sergi Bruguera","Manolo Santana","Arancha Sánchez Vicario",
    "Edurne Pasaban","Edurne Eguino","Alejandro Valverde","Samuel Sánchez","Joaquim Rodríguez",
    "Mikel Landa","Enric Mas","Mireia Lalaguna","Almudena Cid","Lidia Valentín","Hugo Sánchez",
    "Pau Donés (no)","Joane Somarriba","Pedro Delgado","Miguel Induráin",
  ],
  "productos-alimentacion": [
    "Pasta","Arroz","Pan","Harina","Leche","Queso","Yogur","Mantequilla","Huevos","Cereales",
    "Aceite de oliva","Sal","Azúcar","Café","Té","Chocolate","Manzana","Plátano","Naranja","Fresa",
    "Sandía","Tomate","Patata","Cebolla","Zanahoria","Lubina","Salmón","Atún","Ternera","Pollo",
    "Cerdo","Jamón","Aceitunas","Galletas","Miel","Vino","Cerveza","Agua","Refresco","Zumo","Pizza",
    "Hamburguesa","Bocadillo","Tortilla","Croqueta","Ensalada","Sopa","Flan","Helado","Tarta",
    "Bizcocho","Magdalena","Donut","Lentejas","Garbanzos","Judías","Quinoa","Avena","Maíz","Trigo",
    "Lechuga","Pepino","Pimiento","Berenjena","Calabaza","Calabacín","Brócoli","Coliflor","Espárragos",
    "Champiñones","Limón","Mandarina","Uva","Pera","Melocotón","Albaricoque","Ciruela","Cerezas",
    "Coco","Piña","Mango","Aguacate","Cordero","Pavo","Chorizo","Sardina","Bacalao","Merluza",
    "Gambas","Mejillones","Almejas","Pulpo","Calamares",
  ],
};

// === NUEVOS TEMAS: Compras/Hogar y Personas/Vida ===
const nuevos = {
  // Compras / Hogar
  "hogar-muebles": [
    "Sofá","Sillón","Silla","Mesa de comedor","Mesa de centro","Mesilla de noche","Cama","Cama nido",
    "Litera","Cuna","Armario","Cómoda","Estantería","Librería","Cabecero","Aparador","Vitrina",
    "Escritorio","Silla giratoria","Taburete","Banco","Banqueta","Otomana","Diván","Chaise longue",
    "Tumbona","Hamaca","Tocador","Cajonera","Espejo de pie","Perchero","Mueble bar","Mueble TV",
    "Galán de noche","Mesa plegable","Mesa baja","Mesa alta","Mesita auxiliar","Pouf","Sofá cama",
    "Sillón reclinable","Mecedora","Trona","Sillón de oficina","Banca","Mueble zapatero","Sinfonier",
    "Cómoda con cajones","Coqueta","Vestidor","Closet",
  ],
  "hogar-electrodomesticos": [
    "Frigorífico","Congelador","Lavadora","Secadora","Lavavajillas","Vitrocerámica","Inducción",
    "Placa de gas","Horno","Microondas","Campana extractora","Cafetera","Cafetera de cápsulas",
    "Cafetera espresso","Hervidor","Tostadora","Sandwichera","Gofrera","Plancha","Centro de planchado",
    "Aspiradora","Aspiradora robot","Aspiradora escoba","Robot de cocina","Thermomix","Mambo",
    "Olla GM","Freidora de aire","Air fryer","Olla express","Olla a presión","Yogurtera","Heladera",
    "Báscula de cocina","Batidora","Batidora de vaso","Robot Kitchenaid","Exprimidor","Licuadora",
    "Extractor de zumo","Plancha de pelo","Secador","Cepillo eléctrico","Depiladora","Afeitadora",
    "Cortapelos","Aire acondicionado","Calefactor","Estufa","Humidificador","Purificador de aire",
    "Ventilador","Ventilador de techo",
  ],
  "hogar-cocina": [
    "Tenedor","Cuchara","Cucharilla","Cuchillo","Pala","Espátula","Cucharón","Cazo","Sartén","Olla",
    "Cazuela","Wok","Plancha","Parrilla","Bandeja","Fuente","Plato","Vaso","Copa","Taza","Mug",
    "Jarra","Botella","Cuenco","Bol","Ensaladera","Sopera","Salsera","Salero","Pimentero","Aceitera",
    "Vinagrera","Especiero","Tabla de cortar","Pelapatatas","Rallador","Mortero","Almirez","Colador",
    "Espumadera","Embudo","Abrelatas","Sacacorchos","Cascanueces","Termómetro de cocina","Báscula",
    "Rodillo","Molde","Molde de tarta","Cortagalletas","Manga pastelera","Cucharón medidor",
    "Vaso medidor","Tupper","Bote hermético","Film transparente","Papel de aluminio","Papel vegetal",
    "Servilleta","Mantel","Posavasos","Salvamantel",
  ],
  "hogar-decoracion": [
    "Cuadro","Lámpara","Lámpara de pie","Lámpara de mesa","Lámpara de techo","Aplique","Plafón","Vela",
    "Candelabro","Velón","Espejo","Marco","Estatua","Figura decorativa","Jarrón","Florero","Flor seca",
    "Planta","Maceta","Tiesto","Alfombra","Cortina","Estor","Persiana","Visillo","Cojín","Manta",
    "Tapiz","Mural","Vinilo decorativo","Reloj de pared","Reloj de mesa","Caja decorativa",
    "Bandeja decorativa","Cesto","Cesta de mimbre","Baúl","Cuadro abstracto","Cuadro paisaje",
    "Póster","Lámina","Letras decorativas","Cartel","Estantería decorativa","Repisa","Bolas decorativas",
    "Velas aromáticas","Difusor","Centro de mesa","Atrapasueños","Móvil decorativo","Bola del mundo",
    "Pizarra","Corcho","Móvil colgante","Banderines","Guirnalda","Luces de Navidad",
  ],
  // Personas / Vida y aficiones
  "personas-aficiones": [
    "Leer","Escribir","Dibujar","Pintar","Tocar la guitarra","Tocar el piano","Cantar","Bailar",
    "Cocinar","Hornear","Tejer","Coser","Bordar","Hacer punto","Fotografía","Jardinería","Bricolaje",
    "Carpintería","Pesca","Caza","Camping","Senderismo","Montañismo","Esquí","Snowboard","Surf","Skate",
    "Patinaje","Ciclismo","Running","Yoga","Pilates","Meditación","Crossfit","Bailar salsa",
    "Bailar flamenco","Bailar tango","Karaoke","Cine","Series","Videojuegos","Coleccionismo","Filatelia",
    "Numismática","Ajedrez","Sudoku","Crucigramas","Rompecabezas","Manualidades","Origami","Macramé",
    "Patchwork","Scrapbooking","Pintura al óleo","Acuarela","Cerámica","Escultura","Modelismo","Maquetas",
    "Astronomía","Birdwatching","Apicultura","Buceo","Snorkel","Vela","Remo","Piragüismo","Equitación",
    "Tiro con arco",
  ],
  "personas-deportes": [
    "Fútbol","Baloncesto","Tenis","Pádel","Golf","Béisbol","Rugby","Hockey","Voleibol","Balonmano",
    "Bádminton","Tenis de mesa","Natación","Buceo","Surf","Vela","Remo","Piragüismo","Kayak","Esquí",
    "Snowboard","Patinaje","Hockey hielo","Curling","Ciclismo","BMX","MTB","Triatlón","Maratón",
    "Running","Atletismo","Cross country","Senderismo","Escalada","Montañismo","Alpinismo","Trekking",
    "Boxeo","Karate","Judo","Taekwondo","Kickboxing","Jiu-Jitsu","MMA","Lucha grecorromana","Lucha libre",
    "Yoga","Pilates","Crossfit","Gimnasio","Halterofilia","Powerlifting","Esgrima","Tiro con arco",
    "Tiro deportivo","Equitación","Polo","Doma","Gimnasia rítmica","Gimnasia artística","Trampolín",
    "Skate","Ballet","Danza contemporánea","Hip hop","Zumba","Aerobic","Pesca deportiva","Caza",
  ],
  "personas-edades": [
    "Recién nacido","Bebé","Niño pequeño","Niña pequeña","Niño","Niña","Preadolescente","Adolescente",
    "Joven","Adulto joven","Adulto","Adulta","Mediana edad","Maduro","Adulto mayor","Anciano","Anciana",
    "Tercera edad","Cuarta edad","Centenario","Veinteañero","Treintañero","Cuarentón","Cincuentón",
    "Sesentón","Setentón","Octogenario","Nonagenario","Niñez","Infancia","Pubertad","Adolescencia",
    "Juventud","Madurez","Vejez","Senectud","Lactante","Quinceañera","Universitario","Jubilado",
    "Pensionista","Generación Z","Millennial","Generación X","Baby boomer","Generación silenciosa",
    "Nativo digital",
  ],
};

function appendNew(filePath, nuevos, isNew = false) {
  const data = isNew || !existsSync(filePath) ? [] : JSON.parse(readFileSync(filePath, "utf-8"));
  const seen = new Set(data.map((it) => norm(it.nombre || "")));
  let added = 0;
  for (const nombre of nuevos) {
    const key = norm(nombre);
    if (key && !seen.has(key)) {
      data.push({ nombre, imagen: "" });
      seen.add(key);
      added++;
    }
  }
  writeFileSync(filePath, JSON.stringify(data, null, 2));
  return { added, total: data.length };
}

console.log("\n=== Sumar a temas existentes sin fotos ===");
for (const [slug, lista] of Object.entries(lists)) {
  const p = join(ROOT, "public", "data", "mundo", slug + ".json");
  const r = appendNew(p, lista);
  console.log(`  ${slug.padEnd(28)} +${r.added} (total ${r.total})`);
}

console.log("\n=== Crear nuevos temas (hogar-*, personas-*) ===");
for (const [slug, lista] of Object.entries(nuevos)) {
  const p = join(ROOT, "public", "data", "mundo", slug + ".json");
  const wasNew = !existsSync(p);
  const r = appendNew(p, lista, wasNew);
  console.log(`  ${slug.padEnd(28)} ${wasNew ? "NUEVO " : "existía "}+${r.added} (total ${r.total})`);
}
